channels:
  - defaults
dependencies:
  - pandas
  - plotnine
  - scikit-learn
  - spyder-kernels
  - xlrd
  - pip
  - pip:
    - git+https://github.com/woodcrafty/PyETo.git@8ca15bd6f70eda39f42b40581e7d5cab4bf76fbc#egg=PyETo
  - python=3.7.*